name: Reusable Build

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: true
        type: string
    secrets:
      KEY_SSH:
        required: true

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Build and update Summary
        id: build_step
        run: |
          start=$(date +%s%3N)
          if bun run build; then
            status="success"
            exit_code=0
          else
            status="failed"
            exit_code=1
          fi
          end=$(date +%s%3N)
          duration_ms=$((end - start))
          echo "status=$status" >> $GITHUB_OUTPUT
          echo "duration_ms=$duration_ms" >> $GITHUB_OUTPUT
          exit $exit_code

      - name: Final Summary
        run: |
          status="${{ steps.build_step.outputs.status }}"
          duration_ms="${{ steps.build_step.outputs.duration_ms }}"
          if [ "$status" = "success" ]; then
            status_icon="✅ Success"
          else
            status_icon="❌ Failed"
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 🏗️ Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Duration (ms) |" >> $GITHUB_STEP_SUMMARY
          echo "|:------:|:-------------:|" >> $GITHUB_STEP_SUMMARY
          echo "| $status_icon | $duration_ms |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "$status" = "success" ]; then
            echo "Build completed successfully." >> $GITHUB_STEP_SUMMARY
          else
            echo "Build failed. See logs above for details." >> $GITHUB_STEP_SUMMARY
          fi
