name: Create canary release
run-name: Create Canary Release

on:
  push:
    branches:
      - develop # Trigger on push to develop branch

permissions:
  contents: write   # allow push, tag, release

# Secrets used in the workflow
# KEY_SSH: SSH key to access the repository (used with deploy keys)
# KEY_GPG: GPG key to sign commits or tags
# GIT_EMAIL: Email address used for git commits
# NPM_TOKEN: NPM token for publishing packages

jobs:
  lint:
    if: contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, 'merge')
    uses: ./.github/workflows/lint.yml
    with:
      branch: develop
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      KEY_GPG: ${{ secrets.KEY_GPG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      branch: develop
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml
    with:
      branch: develop
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}

  create-suffix:
    runs-on: ubuntu-latest
    needs: unit-test
    outputs:
      versionSuffix: ${{ steps.prepare-version.outputs.versionSuffix }}
    steps:
      - name: Prepare version suffix
        id: prepare-version
        run: |
          short_sha="${GITHUB_SHA::7}"
          date_part=$(date +%Y%m%d)
          echo "versionSuffix=canary-${date_part}-${short_sha}" >> $GITHUB_OUTPUT

  create-github-release:
    needs: create-suffix
    uses: ./.github/workflows/create-github-release.yml
    with:
      branch: develop
      versionSuffix: ${{ needs.create-suffix.outputs.versionSuffix }}
      isPrerelease: true
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      KEY_GPG: ${{ secrets.KEY_GPG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: create-github-release
    uses: ./.github/workflows/publish-npm.yml
    with:
      branch: develop
      npmTag: canary
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}