name: Create stable release
run-name: Create stable Release

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow push, tag, release

# Secrets used in the workflow
# KEY_SSH: SSH key to access the repository (used with deploy keys)
# KEY_GPG: GPG key to sign commits or tags
# GIT_EMAIL: Email address used for git commits
# NPM_TOKEN: NPM token for publishing packages


jobs:
  lint:
    if: contains(github.event.head_commit.message, 'Merge') || contains(github.event.head_commit.message, 'merge')
    uses: ./.github/workflows/lint.yml
    with:
      branch: main
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      KEY_GPG: ${{ secrets.KEY_GPG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      branch: main
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}

  unit-test:
    needs: build
    uses: ./.github/workflows/unit-test.yml
    with:
      branch: main
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}

  create-github-release:
    needs: [unit-test]
    uses: ./.github/workflows/create-github-release.yml
    with:
      branch: main
      versionSuffix: ''
      isPrerelease: false
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      KEY_GPG: ${{ secrets.KEY_GPG }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

  doc:
    name: Doc
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          ssh-key: ${{ secrets.KEY_SSH }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Generate Docs
        run: bun run docs

      - name: Upload Coverage
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  publish-npm:
    needs: create-github-release
    uses: ./.github/workflows/publish-npm.yml
    with:
      branch: main
      npmTag: latest
    secrets:
      KEY_SSH: ${{ secrets.KEY_SSH }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}